services:
  redis_1:
    image: "redis:latest"
    container_name: redis_1
    ports:
      - "7000:6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7000    

  redis_2:
    image: "redis:latest"
    container_name: redis_2
    ports:
      - "7001:6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.3
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7001    

  redis_3:
    image: "redis:latest"
    container_name: redis_3
    ports:
      - "7002:6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.4
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7002    

  redis_4:
    image: "redis:latest"
    container_name: redis_4
    ports:
      - "7003:6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.5
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7003    

  redis_5:
    image: "redis:latest"
    container_name: redis_5
    ports:
      - "7004:6379"
    volumes:
      - redis_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.6
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7004    

  redis_6:
    image: "redis:latest"
    container_name: redis_6
    ports:
      - "7005:6379"
    volumes:
      - redis_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.7
    environment:
      - REDIS_CLUSTER_ANNOUNCE_IP=192.168.104.85
      - REDIS_CLUSTER_ANNOUNCE_PORT=7005    

# Ephemeral container to create the Redis cluster connections.
# Once the setup is done, this container shuts down
# and the cluster can be used by the service app container
  cluster_initiator:
    container_name: cluster_initiator
    image: "redis:latest"
    tty: true
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    command: "redis-cli --cluster create 192.168.104.85:7000 192.168.104.85:7001 192.168.104.85:7002 192.168.104.85:7003 192.168.104.85:7004 192.168.104.85:7005 --cluster-replicas 1 --cluster-yes"
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.8

volumes:
  redis_1_data:
    driver: local        
  redis_2_data:
    driver: local        
  redis_3_data:
    driver: local            
  redis_4_data:
    driver: local                
  redis_5_data:
    driver: local                    
  redis_6_data:
    driver: local                    
networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16      
