version: "3.9"
services:
  redis:
    container_name: redis-course
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"      
    command: redis-server --save 20 1 --loglevel warning --requirepass yoursecretpassword
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local      
